<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mohammed-Windows" failures="1" tests="3" name="Error Validations Test" time="34.322" errors="0" timestamp="2025-04-21T19:03:08 IST">
  <testcase classname="rahulshettyacademy.Tests.ErrorValidationsTest" name="loginErrorValidation" time="0.526"/>
  <testcase classname="rahulshettyacademy.Tests.ErrorValidationsTest" name="productErrorValidation" time="12.655">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="rahulshettyacademy.Tests.ErrorValidationsTest" name="productErrorValidation" time="12.726">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rahulshettyacademy.Tests.ErrorValidationsTest.productErrorValidation(ErrorValidationsTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validations Test -->
